import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { HttpClientModule } from '@angular/common/http';
import { Observable } from 'rxjs';

export class UsersService {
    users = [
        {
            "login": "unclebob",
            "id": 36901,
            "node_id": "MDQ6VXNlcjM2OTAx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/36901?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/unclebob",
            "html_url": "https://github.com/unclebob",
            "followers_url": "https://api.github.com/users/unclebob/followers",
            "following_url": "https://api.github.com/users/unclebob/following{/other_user}",
            "gists_url": "https://api.github.com/users/unclebob/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/unclebob/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/unclebob/subscriptions",
            "organizations_url": "https://api.github.com/users/unclebob/orgs",
            "repos_url": "https://api.github.com/users/unclebob/repos",
            "events_url": "https://api.github.com/users/unclebob/events{/privacy}",
            "received_events_url": "https://api.github.com/users/unclebob/received_events",
            "type": "User",
            "site_admin": false,
            "score": 102.635414
        },
        {
            "login": "hrbrmstr",
            "id": 509878,
            "node_id": "MDQ6VXNlcjUwOTg3OA==",
            "avatar_url": "https://avatars2.githubusercontent.com/u/509878?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hrbrmstr",
            "html_url": "https://github.com/hrbrmstr",
            "followers_url": "https://api.github.com/users/hrbrmstr/followers",
            "following_url": "https://api.github.com/users/hrbrmstr/following{/other_user}",
            "gists_url": "https://api.github.com/users/hrbrmstr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hrbrmstr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hrbrmstr/subscriptions",
            "organizations_url": "https://api.github.com/users/hrbrmstr/orgs",
            "repos_url": "https://api.github.com/users/hrbrmstr/repos",
            "events_url": "https://api.github.com/users/hrbrmstr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hrbrmstr/received_events",
            "type": "User",
            "site_admin": false,
            "score": 96.50332
        },
        {
            "login": "bobthecow",
            "id": 53660,
            "node_id": "MDQ6VXNlcjUzNjYw",
            "avatar_url": "https://avatars1.githubusercontent.com/u/53660?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bobthecow",
            "html_url": "https://github.com/bobthecow",
            "followers_url": "https://api.github.com/users/bobthecow/followers",
            "following_url": "https://api.github.com/users/bobthecow/following{/other_user}",
            "gists_url": "https://api.github.com/users/bobthecow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bobthecow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bobthecow/subscriptions",
            "organizations_url": "https://api.github.com/users/bobthecow/orgs",
            "repos_url": "https://api.github.com/users/bobthecow/repos",
            "events_url": "https://api.github.com/users/bobthecow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bobthecow/received_events",
            "type": "User",
            "site_admin": false,
            "score": 83.79466
        },
        {
            "login": "bob",
            "id": 1436,
            "node_id": "MDQ6VXNlcjE0MzY=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1436?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bob",
            "html_url": "https://github.com/bob",
            "followers_url": "https://api.github.com/users/bob/followers",
            "following_url": "https://api.github.com/users/bob/following{/other_user}",
            "gists_url": "https://api.github.com/users/bob/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bob/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bob/subscriptions",
            "organizations_url": "https://api.github.com/users/bob/orgs",
            "repos_url": "https://api.github.com/users/bob/repos",
            "events_url": "https://api.github.com/users/bob/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bob/received_events",
            "type": "User",
            "site_admin": false,
            "score": 82.49976
        },
        {
            "login": "munificent",
            "id": 46275,
            "node_id": "MDQ6VXNlcjQ2Mjc1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/46275?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/munificent",
            "html_url": "https://github.com/munificent",
            "followers_url": "https://api.github.com/users/munificent/followers",
            "following_url": "https://api.github.com/users/munificent/following{/other_user}",
            "gists_url": "https://api.github.com/users/munificent/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/munificent/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/munificent/subscriptions",
            "organizations_url": "https://api.github.com/users/munificent/orgs",
            "repos_url": "https://api.github.com/users/munificent/repos",
            "events_url": "https://api.github.com/users/munificent/events{/privacy}",
            "received_events_url": "https://api.github.com/users/munificent/received_events",
            "type": "User",
            "site_admin": false,
            "score": 79.62372
        },
        {
            "login": "etrepum",
            "id": 26596,
            "node_id": "MDQ6VXNlcjI2NTk2",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26596?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/etrepum",
            "html_url": "https://github.com/etrepum",
            "followers_url": "https://api.github.com/users/etrepum/followers",
            "following_url": "https://api.github.com/users/etrepum/following{/other_user}",
            "gists_url": "https://api.github.com/users/etrepum/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/etrepum/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/etrepum/subscriptions",
            "organizations_url": "https://api.github.com/users/etrepum/orgs",
            "repos_url": "https://api.github.com/users/etrepum/repos",
            "events_url": "https://api.github.com/users/etrepum/events{/privacy}",
            "received_events_url": "https://api.github.com/users/etrepum/received_events",
            "type": "User",
            "site_admin": false,
            "score": 79.15673
        },
        {
            "login": "lordfriend",
            "id": 1235614,
            "node_id": "MDQ6VXNlcjEyMzU2MTQ=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/1235614?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lordfriend",
            "html_url": "https://github.com/lordfriend",
            "followers_url": "https://api.github.com/users/lordfriend/followers",
            "following_url": "https://api.github.com/users/lordfriend/following{/other_user}",
            "gists_url": "https://api.github.com/users/lordfriend/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lordfriend/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lordfriend/subscriptions",
            "organizations_url": "https://api.github.com/users/lordfriend/orgs",
            "repos_url": "https://api.github.com/users/lordfriend/repos",
            "events_url": "https://api.github.com/users/lordfriend/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lordfriend/received_events",
            "type": "User",
            "site_admin": false,
            "score": 77.60343
        },
        {
            "login": "bobuk",
            "id": 1919,
            "node_id": "MDQ6VXNlcjE5MTk=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/1919?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bobuk",
            "html_url": "https://github.com/bobuk",
            "followers_url": "https://api.github.com/users/bobuk/followers",
            "following_url": "https://api.github.com/users/bobuk/following{/other_user}",
            "gists_url": "https://api.github.com/users/bobuk/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bobuk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bobuk/subscriptions",
            "organizations_url": "https://api.github.com/users/bobuk/orgs",
            "repos_url": "https://api.github.com/users/bobuk/repos",
            "events_url": "https://api.github.com/users/bobuk/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bobuk/received_events",
            "type": "User",
            "site_admin": false,
            "score": 76.86159
        },
        {
            "login": "bobtfish",
            "id": 42338,
            "node_id": "MDQ6VXNlcjQyMzM4",
            "avatar_url": "https://avatars1.githubusercontent.com/u/42338?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bobtfish",
            "html_url": "https://github.com/bobtfish",
            "followers_url": "https://api.github.com/users/bobtfish/followers",
            "following_url": "https://api.github.com/users/bobtfish/following{/other_user}",
            "gists_url": "https://api.github.com/users/bobtfish/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bobtfish/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bobtfish/subscriptions",
            "organizations_url": "https://api.github.com/users/bobtfish/orgs",
            "repos_url": "https://api.github.com/users/bobtfish/repos",
            "events_url": "https://api.github.com/users/bobtfish/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bobtfish/received_events",
            "type": "User",
            "site_admin": false,
            "score": 76.853386
        },
        {
            "login": "bobzhang",
            "id": 747051,
            "node_id": "MDQ6VXNlcjc0NzA1MQ==",
            "avatar_url": "https://avatars0.githubusercontent.com/u/747051?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bobzhang",
            "html_url": "https://github.com/bobzhang",
            "followers_url": "https://api.github.com/users/bobzhang/followers",
            "following_url": "https://api.github.com/users/bobzhang/following{/other_user}",
            "gists_url": "https://api.github.com/users/bobzhang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bobzhang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bobzhang/subscriptions",
            "organizations_url": "https://api.github.com/users/bobzhang/orgs",
            "repos_url": "https://api.github.com/users/bobzhang/repos",
            "events_url": "https://api.github.com/users/bobzhang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bobzhang/received_events",
            "type": "User",
            "site_admin": false,
            "score": 76.56046
        },
        {
            "login": "bob-crutchley",
            "id": 41346501,
            "node_id": "MDQ6VXNlcjQxMzQ2NTAx",
            "avatar_url": "https://avatars0.githubusercontent.com/u/41346501?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bob-crutchley",
            "html_url": "https://github.com/bob-crutchley",
            "followers_url": "https://api.github.com/users/bob-crutchley/followers",
            "following_url": "https://api.github.com/users/bob-crutchley/following{/other_user}",
            "gists_url": "https://api.github.com/users/bob-crutchley/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bob-crutchley/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bob-crutchley/subscriptions",
            "organizations_url": "https://api.github.com/users/bob-crutchley/orgs",
            "repos_url": "https://api.github.com/users/bob-crutchley/repos",
            "events_url": "https://api.github.com/users/bob-crutchley/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bob-crutchley/received_events",
            "type": "User",
            "site_admin": false,
            "score": 75.92239
        },
        {
            "login": "iambocai",
            "id": 2259715,
            "node_id": "MDQ6VXNlcjIyNTk3MTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/2259715?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iambocai",
            "html_url": "https://github.com/iambocai",
            "followers_url": "https://api.github.com/users/iambocai/followers",
            "following_url": "https://api.github.com/users/iambocai/following{/other_user}",
            "gists_url": "https://api.github.com/users/iambocai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iambocai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iambocai/subscriptions",
            "organizations_url": "https://api.github.com/users/iambocai/orgs",
            "repos_url": "https://api.github.com/users/iambocai/repos",
            "events_url": "https://api.github.com/users/iambocai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iambocai/received_events",
            "type": "User",
            "site_admin": false,
            "score": 75.78073
        },
        {
            "login": "rjw1",
            "id": 46021,
            "node_id": "MDQ6VXNlcjQ2MDIx",
            "avatar_url": "https://avatars2.githubusercontent.com/u/46021?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rjw1",
            "html_url": "https://github.com/rjw1",
            "followers_url": "https://api.github.com/users/rjw1/followers",
            "following_url": "https://api.github.com/users/rjw1/following{/other_user}",
            "gists_url": "https://api.github.com/users/rjw1/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rjw1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rjw1/subscriptions",
            "organizations_url": "https://api.github.com/users/rjw1/orgs",
            "repos_url": "https://api.github.com/users/rjw1/repos",
            "events_url": "https://api.github.com/users/rjw1/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rjw1/received_events",
            "type": "User",
            "site_admin": false,
            "score": 73.55431
        }];

    constructor(private http: HttpClient) {

    }

    getUsers() {
        return this.users;
    }

    /*getUsers(searchUrl: string) {
        this.http.get(searchUrl)
        .subscribe(response => {
            this.users = response;
        });
        console.log(this.users);
    }*/
}